name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package --out extension.vsix

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.vsix
          generate_release_notes: true
